# Iteratated Proportional Fitting

Iterated Proportional Fitting (IPF) is used to get estimates for the joing distribution given we have the marginal distribution. Below is an example implementing this via a toy example.

In [1]:
import numpy as np
import pandas as pd
from ipf import ipf
from IPython.display import HTML, display
import tabulate

The table below shows a toy table with some initial values and the known marginal distribution. 

In [2]:
table = [['Age/Gender','Age Group 1','Age Group 2','Age Group 3','Gender Group Totals'],
    ['Gender Group 1', 6,6,4,20],
         ['Gender Group 2', 8,10,10,30],
         ['Gender Group 3', 9,10,9,35],
         ['Gender Group 4', 3,14,8,15],
        ['Age Group Totals',35,40,25,]]
display(HTML(tabulate.tabulate(table, tablefmt='html')))

In [3]:
x = np.array([[6,6,3],[8,10,10],[9,10,9],[3,14,8]])
row_total = np.array([20,30,35,15])
col_total = np.array([35,40,25])

In [4]:
ipf = ipf()

In [5]:
ipf.fit(initial_joint = x, marginal1 = row_total, marginal2 = col_total, method = 'mle')

Fitting using mle ...


array([[ 9.45261635,  8.07789398,  3.25052241],
       [10.12780323, 10.81860801,  8.70675644],
       [13.29274174, 12.62170934,  9.14209427],
       [ 2.12683868,  8.48178868,  3.90062689]])

In [6]:
ipf.fit(initial_joint = x, marginal1 = row_total, marginal2 = col_total, method = 'poisson')

Fitting using poisson ...


array([[7.55263315, 8.74399915, 5.63475397],
       [8.6781802 , 9.05881313, 7.96422262],
       [9.3023741 , 9.22044534, 9.46842203],
       [7.04584774, 8.59071892, 4.73958965]])

In [7]:
ipf.fit(initial_joint = x, marginal1 = row_total, marginal2 = col_total, interaction= False, method = 'poisson')

Fitting using poisson ...


array([[ 7.49519304,  8.13707858,  6.35933126],
       [ 8.7870433 ,  9.53956242,  7.45540759],
       [ 9.51421012, 10.32900353,  8.07237565],
       [ 6.92233879,  7.51516531,  5.87329042]])